apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: mar20-testnewgitops-rag-gitops-repository
spec:
  url: https://github.com/jdubrick-ai/mar20-testnewgitops-rag-gitops
